### PR TITLE
Add wishes in PlanSidebar props

### LINKED ISSUE #84: [GFI]: Show total cost of wishes in a plan
### Description

Get the sum of all the prices of wishes in a plan and display the information in the sidebar.

image

### Comments / questions

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kunalkashyap855**
## Proposed Changes

- Add 'wishes' value in PlanSidebar props.
- Create a new section in the sidebar to display total cost.
- A function to calculate total cost using array.reduce() JavaScript method.
Screenshot 2023-02-25 at 1 51 14 AM

Fixes #84

### CODE REVIEW

**Review by Andreasgdp — CHANGES_REQUESTED** [review]
Looks good! You will just need to format the code `yarn format:write`. 

After that your PR will not be held hostage by CodeScene Delta Analysis. The "Plan" files are a bit complex today, and we will need to refactor them at some point.

**Review by Andreasgdp — APPROVED** [review]
Thank you for your work and professionalism 👌

**Comment by Andreasgdp** [comment]
I will make sure to get your changes in when I get home, so no more for you to do on this task.

Don't know why the linting failed (it has nothing to do with your changes it seems).

I am going to re-work the formatting and linting steps soon, so will look at the linting bug then.

**Comment by kunalkashyap855** [comment]
@Andreasgdp Sounds good! Seems like a cool project, nice to work on this!

**Pull request merged**
