### PR TITLE
fix: Plan sidebar number input shows NaN

### PR DESCRIPTION
**Pull request by oraliahdz**
## Proposed Changes

- Added a separate variable to display in Input Field 

Fixes #
Fix for Issue#64
Plan sidebar number input shows NaN
https://github.com/Andreasgdp/Wishing-Plan/issues/64

### CODE REVIEW

**Review by Andreasgdp — CHANGES_REQUESTED** [review]
Your code works, but only in some cases and it is just for the first input field.

You have the right idea with using a string instead of a number. It would be better to only use a single variable though, and just change the type to a string instead of a number then do conversions when checking against values from DB and when setting values in DB i.e.

```TS
useEffect(() => {
	setSavedAmount(props.plan?.currentAmountSaved.toString() ?? '0');
}, [props.plan?.currentAmountSaved]);
```
And
```TS
const submitPlanSettingsChange = (e: React.SyntheticEvent) => {
	e.preventDefault();
	if (
		amountToSave !== props.plan?.amountToSave.toString() ||
		savedAmount !== props.plan?.currentAmountSaved.toString() ||
		firstSaving !== props.plan?.firstSaving ||
		frequency !== props.plan?.frequency
	) {
		props.onPlanSettingsChange(
			Number(amountToSave),
			Number(savedAmount),
			firstSaving,
			frequency,
		);
	}
};
```

The idea was for the first input field to allow negative numbers, which you have done; but if the user e.g., types some random numbers followed by a "-" it will still show NaN.
For the first input this means you will have to create a regex which catches all but first hyphen.
Something like the following; however, a little tuning is needed as pressing "Home" key on keyboard results in weird behaviour.
```TS
const [savedAmount, setSavedAmount] = useState('0');
const handleSavedAmountChange = (value: string) =>
	setSavedAmount(value.replace(/(?!^)-/, ''));
```

For the second input you would just have to remove the hyphen., so something like:
```TS
const [amountToSave, setAmountToSave] = useState('0');
const handleAmountToSaveChange = (value: string) =>
	setAmountToSave(value.replace('-', ''));
```

**Comment by oraliahdz** [comment]
ok, will work on it

**Comment by oraliahdz** [comment]
@Andreasgdp, Thanks for the suggestions, I did some changes to the code

**Review by Andreasgdp — APPROVED** [review]
Good work! Thanks for contributing 😁

**Pull request merged**
